version: 2

run:
  timeout: 5m

linters:
  disable:
    - errcheck

linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Print
      - fmt.Printf
      - fmt.Println
      - fmt.Fprintf
      - fmt.Sscanf

